python minhash_deduplication.py --dataset xin1997/bugsinpy_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/condefects-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/quixbugs-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/refactory_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/sven-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/crossvul-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/g-transeval-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/debug-bench_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/bigcodebench_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/securityeval_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/pythonsaga_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/humaneval-x-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/human-eval-bia_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/evocodebench_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codereview-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codereview-new-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codereval-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-translate-plus-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-switch-plus-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-polish-plus-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-debug-plus-python_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codebenchgen_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/classeval_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/livecodebench-test-generation_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/livecodebench-execution_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/livecodebench-code-generation_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/swe-bench-verified_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/swe-bench_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codescope_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/canitedit_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/mercury_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/biocoder_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/conala-curated_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/mconala-ru_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/mconala-ja_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/mconala-es_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/ds1000_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/apps_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/mbpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/mbpp-sanitized_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
