python minhash_deduplication.py --dataset xin1997/manybugs_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/sven-cpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/crossvul-cpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/g-transeval-cpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/devign_test_set_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/vulnpatchpairs_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/d2a_function_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/d2a_code_trace_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/d2a_code_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/bigvul_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/debug-bench_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/bigcodebench_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/poj104_test_set_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/primevul_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/pareval-translation_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/pareval-generation_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/humaneval-x-cpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/diversevul_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codereview-cpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codereview-new-cpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-translate-plus-cpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-switch-plus-cpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-polish-plus-cpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-debug-plus-cpp_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/big-vul-cvefix-repair_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codescope_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/multipl-e-mbpp-cpp_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/multipl-e-humaneval-cpp_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
