python minhash_deduplication.py --dataset xin1997/bugs-dot-jar_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/defects4j-2.0_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/condefects-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/quixbugs-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/gitbug-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/logbench-t_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/logbench-o_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/vjbench_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/vul4j_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/crossvul-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/g-transeval-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/debug-bench_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/bigclonebench_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/bigcodebench_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/robustness-copilot_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/satd-removal_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/humaneval-x-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codereview-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codereview-new-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codereval-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-translate-plus-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-switch-plus-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-polish-plus-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codeeditorbench-debug-plus-java_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/api-misuse-repair-single_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/api-misuse-repair-complete_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/aixbench-manual_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/aixbench-auto_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/codescope_all_only_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/multipl-e-mbpp-java_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/multipl-e-humaneval-java_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/concode_only_test_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/code-ucb-complete_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/code-ujb-complete_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/code-ujb-defectdetection_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/code-ujb-testgenissue_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/code-ujb-testgen_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
python minhash_deduplication.py --dataset xin1997/code-ujb-repair_all_input --split train --column content --cache_dir ./cache --ngram_size 2 --min_ngram_size 2  --threshold 0.7
